# Generated by Django 2.0.13 on 2019-08-08 06:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('level', models.IntegerField(choices=[(1, 'admin'), (2, 'normal')])),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents')),
                ('document_file2', models.FileField(blank=True, null=True, upload_to='documents')),
                ('document_file3', models.FileField(blank=True, null=True, upload_to='documents')),
                ('document_file4', models.FileField(blank=True, null=True, upload_to='documents')),
                ('document_file5', models.FileField(blank=True, null=True, upload_to='documents')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='johnstonemart.Category')),
                ('user', models.ForeignKey(default=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
    ]
