# Generated by Django 2.0.13 on 2019-08-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnstonemart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
