# Generated by Django 2.0.13 on 2019-08-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnstonemart', '0002_auto_20190814_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.CharField(max_length=60)),
            ],
        ),
    ]
