# Generated by Django 2.0.13 on 2019-08-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnstonemart', '0003_ipaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaccess',
            name='name',
            field=models.CharField(default='john', max_length=60),
            preserve_default=False,
        ),
    ]
