# Generated by Django 2.0.13 on 2019-08-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnstonemart', '0004_ipaccess_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
