# Generated by Django 2.0.13 on 2019-08-22 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('johnstonemart', '0005_category_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='notification',
        ),
    ]
