# Generated by Django 2.0.13 on 2019-09-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnstonemart', '0006_remove_category_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.IntegerField(default=9, verbose_name='Sorted Level'),
        ),
    ]
