# Generated by Django 2.0.13 on 2019-09-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnstonemart', '0007_category_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.CharField(choices=[('ALL', 'ALL'), ('Nunawading', 'Nunawading'), ('Dandenong', 'Dandenong'), ('770 Springvale', '770 Springvale'), ('Rookwood', 'Rookwood'), ('Matravile', 'Matravile'), ('Footscray', 'Footscray'), ('Dandenong South', 'Dandenong South'), ('Thomastown', 'Thomastown'), ('1 Queens Ave Springvale', '1 Queens Ave Springvale')], default='ALL', max_length=40),
        ),
    ]
