# Generated by Django 2.0.13 on 2019-09-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnstonemart', '0008_category_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['level', 'store'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='store',
            field=models.CharField(choices=[('Footscray', 'Footscray'), ('ALL', 'ALL'), ('Rookwood', 'Rookwood'), ('Thomastown', 'Thomastown'), ('Nunawading', 'Nunawading'), ('Dandenong', 'Dandenong'), ('Dandenong South', 'Dandenong South'), ('1 Queens Ave Springvale', '1 Queens Ave Springvale'), ('Matravile', 'Matravile'), ('770 Springvale', '770 Springvale')], default='ALL', max_length=40),
        ),
    ]
