# Generated by Django 2.0.13 on 2019-09-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnstonemart', '0009_auto_20190925_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='store',
            field=models.CharField(choices=[('ALL', 'ALL'), ('Dandenong South', 'Dandenong South'), ('770 Springvale', '770 Springvale'), ('1 Queens Ave Springvale', '1 Queens Ave Springvale'), ('Matravile', 'Matravile'), ('Footscray', 'Footscray'), ('Nunawading', 'Nunawading'), ('Thomastown', 'Thomastown'), ('Rookwood', 'Rookwood'), ('Dandenong', 'Dandenong')], default='ALL', max_length=40),
        ),
    ]
