# Generated by Django 2.0.13 on 2019-10-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('johnstonemart', '0010_auto_20190925_0607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['level', 'name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='store',
            field=models.CharField(choices=[('ALL', 'ALL'), ('Footscray', 'Footscray'), ('Dandenong', 'Dandenong'), ('770 Springvale', '770 Springvale'), ('Nunawading', 'Nunawading'), ('Thomastown', 'Thomastown'), ('Rookwood', 'Rookwood'), ('Matravile', 'Matravile'), ('Dandenong South', 'Dandenong South'), ('1 Queens Ave Springvale', '1 Queens Ave Springvale')], default='ALL', max_length=40),
        ),
    ]
